# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwlogs < Formula
  desc "Fast, terminal-based AWS CloudWatch log viewer"
  homepage "https://github.com/teaguru/cwlogs"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.0.2/cwlogs-1.0.2-Darwin-x86_64.tar.gz"
      sha256 "2e018351e33cdf106565dee100efa8a40219346bb42bdeb658fe92bec0241033"

      def install
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.0.2/cwlogs-1.0.2-Darwin-arm64.tar.gz"
      sha256 "bd7cfdc4b93b91ea0e501a294e0a65f5620c8b424b2189bc83ffc9e773f357b9"

      def install
        bin.install "cwlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.0.2/cwlogs-1.0.2-Linux-x86_64.tar.gz"
      sha256 "33371c4a27cd57e3843e13af53f451a6862bfd83ef9d84a7dbc500dddf775d4c"
      def install
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.0.2/cwlogs-1.0.2-Linux-arm64.tar.gz"
      sha256 "cc5307ded4a998fad6d06da0f7f59ffee31805ca7c6a05adc137d532e1838ed9"
      def install
        bin.install "cwlogs"
      end
    end
  end

  test do
    system "#{bin}/cwlogs --help"
  end
end
