# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwlogs < Formula
  desc "Fast, terminal-based AWS CloudWatch log viewer"
  homepage "https://github.com/teaguru/cwlogs"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.1.1/cwlogs-1.1.1-Darwin-x86_64.tar.gz"
      sha256 "eb7bf4ddfedafa27fe7752ad196a5ed132ae9ea84072a5cb4cfae85405fce838"

      def install
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.1.1/cwlogs-1.1.1-Darwin-arm64.tar.gz"
      sha256 "f05e3073999a54384a8de5d2bf4eba47e46b1e0703d63341b4dc36d9d9103aea"

      def install
        bin.install "cwlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.1.1/cwlogs-1.1.1-Linux-x86_64.tar.gz"
      sha256 "58322a89fb251784061a58b339c194e7a3f45f962bb58a1f3186ca08cd081b1c"
      def install
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teaguru/cwlogs/releases/download/v1.1.1/cwlogs-1.1.1-Linux-arm64.tar.gz"
      sha256 "abd45e0f2917eef631af9f1d09f6f242075d11620800599978e48c23611b34c2"
      def install
        bin.install "cwlogs"
      end
    end
  end

  test do
    system "#{bin}/cwlogs --help"
  end
end
